# 1. Context 

Usage With Surya OCR

In [1]:
from PIL import Image
from surya.foundation import FoundationPredictor
from surya.recognition import RecognitionPredictor
from surya.detection import DetectionPredictor
from surya.layout import LayoutPredictor
import sys
from pathlib import Path

In [17]:
import pandas as pd

In [2]:
notebook_path = Path().resolve()
project_root = notebook_path.parents[1] 
sys.path.append(str(project_root))

In [3]:
from src.ocr.utils import read_json, read_image, get_single_page_gt_jsons, get_single_page_doc_name, get_ocr_results_df
from src.ocr.surya_ocr_infer import SuryaOCR

In [4]:
IMAGE_PATH = "/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/notebooks/surya_ocr/sample_image/sample_5.png"
image = Image.open(IMAGE_PATH)

## 1. OCR (Text Recognition)

## 1.1. Infererence

In [5]:
foundation_predictor = FoundationPredictor()
recognition_predictor = RecognitionPredictor(foundation_predictor)
detection_predictor = DetectionPredictor()

# predictions = recognition_predictor([image], det_predictor=detection_predictor,max_tokens=1024, recognition_batch_size=16)

In [6]:
def post_process_ocr_result(ocr_result) -> str:
    """Post Process OCR Result to get flattend string"""
    ocr_str_flattened = ""
    special_style_tags = ["br","<u>", "</u>", "<b>", "</b>", "<i>", "</i>"]
    replacement_strings = [" ","", "", "", "", "", ""]  
    style_replacements = dict(zip(special_style_tags, replacement_strings))
    for text_line in ocr_result.text_lines:
        ## replace line break <br> with space
        text = text_line.text.replace("<br>", " ")
        for style, str_replace in style_replacements.items():
            ## replace special style tags with empty string
            text = text.replace(style, str_replace)
        ocr_str_flattened += text + " "
    return ocr_str_flattened.strip()

In [ ]:
ocr_result = predictions[0]
ocr_flat = post_process_ocr_result(ocr_result)
gt_json = read_json("/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/gt/Devanagari_Noto_Serif_Devanagari_18.json")
gt_flat = (gt_json['header'] + "\n" + gt_json['full_text']).replace("\n", " ")

In [10]:
IMAGE_PATH_1 = Path("/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/images/level_0/Devanagari_Anek_Devanagari_5_n_pages_1_1.png")
IMAGE_PATH_2 = Path("/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/images/level_0/Devanagari_Anek_Devanagari_11_n_pages_1_1.png")

In [28]:
img_sample_path = [Path('/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/images/level_3/Devanagari_Noto_Serif_Devanagari_7_n_pages_1_1.png'), 
 Path('/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/images/level_3/Devanagari_Poppins_13_n_pages_1_1.png')]

img_data_list = [read_image(img_path) for img_path in img_sample_path]

In [29]:
ocr_surya_obj = SuryaOCR(FoundationPredictor())
predictions = ocr_surya_obj.predict(images_list=img_data_list)
pred_flattened = ocr_surya_obj.post_process(predictions)

Detecting bboxes: 100%|██████████| 1/1 [00:08<00:00,  8.13s/it]
Recognizing Text: 100%|██████████| 20/20 [03:30<00:00, 10.51s/it]

In [30]:
ocr_res_df = get_ocr_results_df(image_path_list, pred_flattened)

In [31]:
ocr_res_df

,file_id,ocr_output_L_3
0,Devanagari_Noto_Serif_Devanagari_7,"इन जानकारी समुचित हुए, संबंधों ग्राहक संबंध प्..."
1,Devanagari_Poppins_13,"के ""एले"" अंग्रेजी भी फ्रांसीसी मोनिका एन्ना मा..."

In [32]:
GT_PATH_1 = Path("/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/gt/Devanagari_Noto_Sans_19.json")
GT_PATH_2 = Path("/Users/niteshkumarsharma/Desktop/Folder/AI/indic_document_extraction/synth_data/hindi/gt/Devanagari_Noto_Serif_Devanagari_18.json")

GT_PATH_LIST = [GT_PATH_1, GT_PATH_2]

In [33]:
file_id_gt_dict = []
for file_gt in GT_PATH_LIST:
    file_nm = file_gt.name.split(".")[0]
    gt_json = read_json(file_gt)
    file_id_gt_dict.append({
        "file_id": file_nm, 
        "ground_truth": (gt_json['header'] + "\n" + gt_json['full_text']).replace("\n", " ")
    })

gt_df = pd.DataFrame(file_id_gt_dict)

In [34]:
gt_df

,file_id,ground_truth
0,Devanagari_Noto_Sans_19,"तंत्र फुफ्फुस गाढ़ा, है। सपूय श्वसन तंत्र के र..."
1,Devanagari_Noto_Serif_Devanagari_18,"से बाद को साइकिल को पृथ्वी का चुंबकीय क्षेत्र,..."

In [35]:
gt_df_ocr = pd.merge(gt_df, ocr_res_df, on='file_id')

In [37]:
gt_df

,file_id,ground_truth
0,Devanagari_Noto_Sans_19,"तंत्र फुफ्फुस गाढ़ा, है। सपूय श्वसन तंत्र के र..."
1,Devanagari_Noto_Serif_Devanagari_18,"से बाद को साइकिल को पृथ्वी का चुंबकीय क्षेत्र,..."

In [38]:
ocr_res_df

,file_id,ocr_output_L_3
0,Devanagari_Noto_Serif_Devanagari_7,"इन जानकारी समुचित हुए, संबंधों ग्राहक संबंध प्..."
1,Devanagari_Poppins_13,"के ""एले"" अंग्रेजी भी फ्रांसीसी मोनिका एन्ना मा..."