# 1. Context

This notebook analyzes OCR performance of Tesseract over synthetic generated PDF images across variois degradation levels

# 2. Imports

In [ ]:
import pandas as pd
from pathlib import Path
from collections import defaultdict

In [85]:
import plotly.graph_objects as go
fig = go.Figure()
from plotly.subplots import make_subplots

# 2. Extracted Results MetaData

In [ ]:
writing_system_to_language = {'Devanagari': ['hindi','sanskrit','nepali','konkani'],
                              'tamil': ['tamil'],'telugu': ['telugu'],'Kannada': ['kannada'],'Malayalam': ['malayalam'],
                              'Bengali': ['bengali', 'assamese', 'manipuri'],'Meetei-mayek': ['manipuri'],'Gujarati': ['gujarati'],
                              'Gurmukhi': ['punjabi'],'Odia': ['oriya'],'Arabic': ['kashmiri', 'sindhi', 'urdu'],
                              'Latin': ['english'],'Ol-chiki': ['santali']}

## 2.1. Language Results Available

In [18]:
results_root = Path("../results/tesseract")

In [32]:
results_langs = [x.name.lower() for x in results_root.glob("*") if x.is_dir()]

In [33]:
language_to_writing_system = {
    "marathi": ["Devanagari"], "hindi": ["Devanagari"], "sanskrit": ["Devanagari"],
    "tamil": ["tamil"], "telugu": ["telugu"], "kannada": ["Kannada"],"malayalam": ["Malayalam"],
    "bengali": ["Bengali"], "assamese": ["Bengali"],"manipuri": ["Bengali", "Meetei-mayek"],"nepali": ["Devanagari"],
    "gujarati": ["Gujarati"], "punjabi": ["Gurmukhi"], "konkani": ["Devanagari"],"oriya": ["Odia"],"kashmiri": ["Devanagari", "Arabic"], 
    "sindhi": ["Arabic", "Devanagari"], "urdu": ["Arabic"],"english": ["Latin"], "santali": ["Ol-chiki", "Devanagari"],
    }

In [51]:
writing_sys_tessract_dict = defaultdict(list)

for language_res in results_langs:
    script = language_to_writing_system.get(language_res)[0]
    writing_sys_tessract_dict[script].append(language_res)

In [59]:
script_language_result = pd.Series(writing_sys_tessract_dict).to_frame(name='languages')
script_language_result.index.name = 'script'

In [78]:
def get_language_results_path(script: str, script_language_result: pd.DataFrame) -> list[Path]:
    """Get list of results path for given script"""

    results_script_lang = script_language_result.loc[script].to_list()[0]
    results_script_lang_path = [results_root.joinpath(lang).joinpath('results.csv') for lang in results_script_lang]

    return results_script_lang_path

In [88]:
script_language_result

                            languages
script
Gujarati                   [gujarati]
Gurmukhi                    [punjabi]
Devanagari  [hindi, sanskrit, nepali]
telugu                       [telugu]
Bengali           [assamese, bengali]
Latin                       [english]
Kannada                     [kannada]
tamil                         [tamil]

# 3. Results Across Various Writing System

## 3.1. Devanagari

In [83]:
script = 'Devanagari'
results_devanagari_path = get_language_results_path(script, script_language_result)

In [81]:
results_list = []
for result_path in results_devanagari_path:
    lang = result_path.parent.name
    df_res = pd.read_csv(result_path)
    df_res['language'] = lang
    results_list.append(df_res)

results_devanagari = pd.concat(results_list)

In [84]:
lang_list = list(results_devanagari['language'].unique())

fig = make_subplots(rows=results_devanagari['language'].nunique(), 
                    cols=1, 
                    shared_yaxes=True,
                    subplot_titles=lang_list)

degrad_level_cer = ['cer_l0', 'cer_l1', 'cer_l2','cer_l3']

for idx, language in enumerate(lang_list):
    results_lang = results_devanagari.loc[results_devanagari['language'] == language]
    for cer_level in degrad_level_cer:
        fig.add_trace(go.Box(y=results_lang[cer_level] * 100,
                                name=cer_level,
                                text=results_lang['file_id']), 
                                row=idx + 1, col=1)


fig.update_layout(height=1200, width=1400)
fig.update_layout(showlegend=False, title_text=f"CER % across various degradation level in {script} languages")
fig.update_yaxes(title_text="CER in %")
fig.show()

In [86]:
lang_list = list(results_devanagari['language'].unique())

fig = make_subplots(rows=results_devanagari['language'].nunique(), 
                    cols=1, 
                    shared_yaxes=True,
                    subplot_titles=lang_list)

degrad_level_wer = ['wer_l0', 'wer_l1', 'wer_l2','wer_l3']

for idx, language in enumerate(lang_list):
    results_lang = results_devanagari.loc[results_devanagari['language'] == language]
    for wer_level in degrad_level_wer:
        fig.add_trace(go.Box(y=results_lang[wer_level] * 100,
                                name=wer_level,
                                text=results_lang['file_id']), 
                                row=idx + 1, col=1)


fig.update_layout(height=1200, width=1400)
fig.update_layout(showlegend=False, title_text=f"WER % across various degradation level and {script} languages")
fig.update_yaxes(title_text="WER in %")
fig.show()

In [87]:
results_lang

,file_id,ground_truth,ocr_output_L_0,ocr_output_L_1,ocr_output_L_2,ocr_output_L_3,cer_l0,cer_l1,cer_l2,cer_l3,wer_l0,wer_l1,wer_l2,wer_l3,language
0,Devanagari_Poppins_24,रूपमा यो राष्ट्रिय पनि भित्र सयौँ थुङ्गा फूलका...,"रुपमा यो राष्ट्रिय पनि भित्र थि ] का हामी मी,...",रुपमा यो राष्ट्रिय पनि भित्र दि ] का द्वामी ह...,रुपमा यो राष्ट्रिय पनि भित्र नेपालको राष्ट्रि...,"रुपमा यो राष्ट्रिय पनि भित्र न कामी मी, नेपाल...",0.636898,0.693890,0.743243,0.661575,0.798450,0.841085,0.895349,0.841085,nepali
1,Devanagari_Noto_Sans_5,"ट्रिनिडाड वैदिक, श्रुति पुरानो संस्कृतमा हिन्द...","ट्रिनिडाड वैदिक, श्रुति पुरानो संस्कृतमा हिन्...","ट्रिनिडाड वैदिक, श्रुति पुरानो संस्कृतमा हिन्...","ट्रिनिडाड वैदिक, श्रुति पुरानो संस्कृतमा एक ज...",' गति पुरानो संस्कृतमा ' जसलाई प्रायः धार्मिक...,0.287570,0.188312,0.234230,0.460575,0.445161,0.325806,0.377419,0.632258,nepali
2,Devanagari_Noto_Sans_Devanagari_21,ठुलो लगभग वर्षाको वर्षाको र वर्षा वायुमण्डलमा ...,ठुलो लगभग वर्षाको वर्षाको र वर्षा वायुमण्डलमा...,ठुलो लग भग वर्षाको वर्षाको र वर्षा वायुमण्डलम...,ठुलो लग भग वर्षाको वर्षाको र वर्षा वायुमण्डलम...,लौ लगभग वर्षाको वर्षाको र अत्यधिक गह्रौँ बा थ...,0.095977,0.103448,0.258621,0.478161,0.219697,0.200758,0.337121,0.647727,nepali
3,Devanagari_Noto_Sans_14,"एपल, आई.एस.ओ/आई.ई.सी. को सहायक होने याहा कोहि ...","एपल, आई.एस.ओ/आई.ई.सी. को सहायक होने याहा को [...","एपल, आई.एस.ओ/आई.ई.सी. को सहायक होने ना 1 कोहि...","एपल, आई.एस.ओ।आई.ई.सी. को सहायक होने गो (॥0८०५...","एपल, आई.एस.ओ/आई.ई.सी. को सहायक होने सा 1 कोहि...",0.200722,0.201238,0.185759,0.327657,0.322581,0.312903,0.267742,0.454839,nepali
4,Devanagari_Noto_Serif_Devanagari_1,"र कडा ""नीलो सूर्यको जीवित पृथ्वी सूर्यको दूरी ...","र कडा ""नीलो सूर्यको जीवित पृथ्वी सूर्यको दूरी...","र कडा ""नीलो सूर्यको जीवित पृथ्वी.सूर्यको दूरी...",पृथ्वी सूर्यको दूरी अनुसार सौर्यमण्ड्लमा रहेका...,"र कडा ""नीलो सूर्यको जीवित पृथ्वी सूर्यको दूरी...",0.231347,0.254382,0.496745,0.237356,0.336601,0.343137,0.689542,0.362745,nepali
5,Devanagari_Poppins_29,देखिन्छ। यो २८२२ प्रयोग वास्तविक इलेक्ट्रोनिक ...,देखिन्छ। यो 2822 प्रयोग वास्तविक हलेक्ट्रोनिक...,देखिन्छ। यो 2822 प्रयोग वास्तविक हलेक्ट्रोनिक...,देखिन्छ। यो 2822 प्रयोग वास्तविक इलेक्ट्रोनिक...,देखिन्छ। यो 2822 प्रयोग वास्तविक हुँनैडसि जि ...,0.482893,0.498445,0.527216,0.684292,0.718750,0.708333,0.755208,0.885417,nepali
6,Devanagari_Noto_Sans_18,गरे। ५ चन्द्रमा उनिहरूको निर्माण थोमस जेफरी ह्...,गरे। ५ चन्द्रमा उनिहरूको निर्माण थोमस जेफरी ह...,गरे। ५ चन्द्रमा उनिहरूको निर्माण थोमस जेफरी ह...,गरे। ५ चन्द्रमा उनिहरूको निर्माण थोमस जेफरी ह...,गरे। ५ चन्द्रमा उनिहरूको निर्माण जेफरी ह्याङ्...,0.121487,0.227108,0.234814,0.256573,0.266881,0.392283,0.369775,0.440514,nepali
7,Devanagari_Poppins_25,रूपमा भनेको धमिलो नाटकको र साहित्य भन्नाले सम्...,रुपमा भनेको धमिलो नाटकको र साहित्य भन्नाले सम...,रुपमा भनेको धमिलो नाटकको र साहित्य भन्नाले सम...,रुपमा भनेको धमिलो नाटकको र ल्ठिखित डि उ म ता ...,रुपमा भनेको धमिलो नाटकको र साहित्य भन्नाले अम...,0.498711,0.545747,0.578608,0.657861,0.686957,0.721739,0.765217,0.817391,nepali
8,Devanagari_Noto_Serif_Devanagari_23,हुन्छ। सक्छ हुन बगैंचा पनि पुस्तक वा किताब शव्...,हुन्छ। सक्छ हुन बगैंचा पनि पुस्तक वा किताब शव...,हुन्छ। सक्छ हुन बगैंचा पनि पुस्तक वा किताब शव...,हुन्छ। सक्छ हुन बगैंचा पनि पुस्तक वा किताब शव...,हुन्छ। सक्छ हुन बगैंचा पनि पुस्तक वा किताब शब...,0.159743,0.126390,0.209479,0.286132,0.297297,0.235521,0.351351,0.440154,nepali
9,Devanagari_Poppins_22,"भिसिआरबाट रे हो, सामान्यतया एक टेलिभिजन (अङ्ग्...","भिसिआरबाट रे हो, सामान्यतया एक ठेलिभिजन (भङ्ग...","भिसिआरबाट रे हो, सामान्यतया एक क (भङ्ग्रेण (2...","भिसिआरबाट रे हो, सामान्यतया एक पर्दा भएको एक ...","भिसिआरबाट रे हो, सामान्यतया एक अखिल त छोटकरीम...",0.553714,0.657714,0.688571,0.754286,0.743295,0.800766,0.812261,0.869732,nepali
10,Devanagari_Noto_Sans_12,जब विभागका यसको लाईट' फिट सगरमाथा संसारको सबैभ...,जब विभागका यसको लाईट' फिट सगरमाथा संसारको सबै...,जब विभागका यसको लाईट' फिट सगरमाथा संसारको सबै...,जब विभागका यसको लाईट' फिट म संसारको सबैभन्दा ...,जब विभागका यसको लाईट' फिट सगरमाथा संसारको सबै...,0.109896,0.130729,0.167708,0.288542,0.210356,0.213592,0.275081,0.398058,nepali
11,Devanagari_Noto_Serif_Devanagari_7,लागि सम्पदाको एकस्थानबाट बरफको बनेको पानी एक र...,लागि सम्पदाको एकस्थानबाट बरफको बनेको पानी एक ...,लागि सम्पदाको एकस्थानबाट बरफको बनेको पानी एक ...,लागि सम्पदाको एकस्थानबाट बरफको बनेको पानी एक ...,नय सम्पदाको एकस्थानबाट बरफको बनेको एक रङ रथ ह...,0.128983,0.138232,0.230216,0.499486,0.222581,0.225806,0.341935,0.638710,nepali
12,Devanagari_Anek_Devanagari_10,"हाम्रो दिशा शास्त्र छ अघि ग्रह, तारा, सौर्यमण्...","हाम्रो दिशा शास्त छ अघि ग्रह, तारा, सौर्यमण्ड...","हाम्रो दिशा शास्त छ अघि ग्रह, तारा, सौर्यमण्ड...","हाम्रो दिशा शास्त छ अघि ग्रह तारा, सौर्यमण्डल...","हाम्रो दिशा शास्त छ अघि तारा, सौर्यमण्डल, तार...",0.076613,0.080141,0.156754,0.282258,0.173633,0.163987,0.279743,0.401929,nepali
13,Devanagari_Noto_Sans_Devanagari_28,मात्र भएको को हदसम्म मिल्दोजुल्दो चन्द्रमा पृथ...,मात्र भएको को हदसम्म मिल्दोजुल्दो चन्द्रमा पृ...,मात्र भएको को हदसम्म मिल्दोजुल्दो चन्द्रमा पृ...,मात्र भएको को हदसम्म मिल्दोजुल्दो चन्द्रमा पृ...,NaN,0.136293,0.133956,0.120717,1.000000,0.250000,0.225000,0.180000,1.000000,nepali
14,Devanagari_Anek_Devanagari_26,"इन्फ्रसाउण्ड रिफ्लेक्सन, गर्दछ| इन्फ्रसाउण्ड ह...","इन्फ्रसाउण्ड रिफ्लेक्सन, गर्दछ| इन्फ्रसाउण्ड ह...","इन्फ्रसाउण्ड रिफ्लेक्सन, गर्दछ] इन्फ्रसाउण्ड ह...","दैन्फसाउपड रिफ्लेक्सन, बैछ इन््रसाङण्ड हुन्छन्...","इन्फ्रसाउण्ड रिफ्लेक्सन, गर्दछ| इन्क्रसाउण्ड ह...",0.116606,0.136142,0.600122,0.373016,0.289474,0.293860,0.793860,0.592105,nepali
15,Devanagari_Anek_Devanagari_30,"देश, र सरकारका भन्नाले गर्न, सरकार मानिसहरूको ...","देश, र सरकारका भन्नाले गर्न, सरकार मानिसहरूको...","देश, र सरकारका भन्नाले गर्न, सरकार मानिसहरूको...","देश, र सरकारका भन्नाले गर्न, सरकार मानिसहरूको...","देश, र सरकारका भन्नाले गर्न, मानिसहरूको जो सँ...",0.070274,0.068869,0.154603,0.264933,0.230769,0.208791,0.296703,0.417582,nepali
16,Devanagari_Noto_Serif_Devanagari_27,"र पनि अन्य ब्रह्मपुत्र नदीहरू, हिमालय एसियाको ...","र पनि अन्य ब्रहापुत्र नदीहरु, हिमालय एसियाको ...","र पनि अन्य ब्रहापुत्र नदीहरु, हिमालय एसियाको ...","र पनि अन्य ब्रहमपुत्र नदीहरु, हिमालय एसियाको ...",NaN,0.221632,0.258129,0.349701,1.000000,0.383886,0.421801,0.497630,1.000000,nepali
17,Devanagari_Anek_Devanagari_3,"बनाइरहेका पनि सोच्यौं, निर्वाचित गिरिजाप्रसाद ...","बनाइरहेका पनि सोच्यौं, निर्वाचित गिरिजाप्रसाद ...","बनाइरहेका पनि सोच्यौं, निर्वाचित गिरिजाप्रसाद ...","बनाइरहेका पनि सोच्यौं, निर्वाचित गिरिजाप्रसाद ...","बनाइरहेका पनि सोच्यौं, निर्वाचित गिरिजाप्रसाद ...",0.038552,0.077104,0.199812,0.222849,0.137821,0.176282,0.339744,0.362179,nepali
18,Devanagari_Noto_Sans_Devanagari_13,अर्थ ग्रन्थका २. हो। गरिएको ऋग्वेद सनातन धर्म ...,अर्थ ग्रन्थका २. हो। गरिएको त्र्ववेद सनातन धर...,अर्थ ग्रन्थका २. हो। गरिएको त्रद्गवेद सनातन ध...,अर्थ ग्रन्थका २. हो। गरिएको त्रष्ग्वेद सनातन ...,अर्थ ग्रन्थका २. हो। गरिएको त्रस्ववेद सनातन ध...,0.222534,0.242637,0.266012,0.411407,0.416938,0.413681,0.478827,0.618893,nepali
19,Devanagari_Anek_Devanagari_4,– तारापुञ्जहरू वृहस्पति अध्ययन अपौरूषेय ज्योति...,- तारापुञ्जहरू वृहस्पति अध्ययन अपौरूषेय ज्योत...,- तारापुञ्जहरू वृहस्पति अध्ययन अपौरूषेय ज्योत...,- तारापुञ्जहरू वृहस्पति अध्ययन अपौरूषेय ज्योत...,- तारापुञ्जहरू बृहस्पति अध्ययन अपौरूषेय ज्योत...,0.123493,0.132658,0.155813,0.491558,0.339869,0.346405,0.437908,0.656863,nepali
20,Devanagari_Noto_Serif_Devanagari_2,हो। कायम पनि वि.सं. राजधानी नेपाल (आधिकारिक ना...,हो। कायम पनि वि.सं. राजधानी नेपाल (आधिकारिक न...,हो। कायम पनि वि.सं. राजधानी नेपाल (आधिकारिक न...,हो। कायम पनि वि.सं. राजधानी नेपाल (आधिकारिक न...,सो। कायम पनि वि.सं. राजधानी यो नेपाल (आधिकारि...,0.104499,0.137397,0.107886,0.538462,0.224756,0.218241,0.185668,0.693811,nepali
21,Devanagari_Anek_Devanagari_8,प्रतिक पशुपतिको चारकुने इन्द्रध्वज कार्मुक नेप...,प्रतिक पशुपतिको चारकुने इन्द्रध्वज कार्मुक ने...,प्रतिक पशुपतिको चारकुने इन्द्रध्वज कार्मुक ने...,प्रतिक पशुपतिको चारकुने इन्द्रध्वज कार्मुक ने...,प्रतिक पशुपतिको चारकुने ड्न्द्धध्वज कार्मुक न...,0.097645,0.124632,0.142787,0.202650,0.217532,0.246753,0.272727,0.383117,nepali
22,Devanagari_Noto_Sans_Devanagari_9,आकाशको अर्थात् बढी चुम्बकीय वस्तुको सूर्य (प्र...,आकाशको अर्थात्‌ बढी चुम्बकीय वस्तुको सूर्य (प...,रै अर्थात्‌ बढी चुम्बकीय वस्तुको सूर्य (प्रती...,आकाशको अर्थात्‌ बढी चुम्बकीय वस्तुको प्रतीक: ...,आकाशको अर्थात्‌ बढी चुम्बकीय वस्तुको सूर्य (प...,0.171846,0.145480,0.202919,0.373352,0.283388,0.254072,0.381107,0.524430,nepali
23,Devanagari_Noto_Sans_16,अगष्ट भएका थिए। 'राजा १९९५ विषेशत चलचित्रलाई ...,अगष्ट भएका थिए। 'राजा १९९५ विषेशत वल िजुला यस...,अगष्ट भएका थिए। 'राजा १९९५ विषेशत लल चना यसरी...,अगष्ट भएका थिए। 'राजा १९९५ विषेशत दिनलाई यसरी...,अगष्ट भएका थिए। 'राजा १९९५ विषेशत 00. परिभाषि...,0.113569,0.139626,0.157325,0.130777,0.211039,0.233766,0.295455,0.211039,nepali
24,Devanagari_Anek_Devanagari_17,कथनलाई अभिव्यक्त वटा स्याउ अध्ययन गणित सङ्ख्या...,कथनलाई अभिव्यक्त वटा स्याउ अध्ययन गणित सङ्ख्य...,कथनलाई अभिव्यक्त वटा स्याउ अध्ययन गणित सङ्ख्य...,आदिको वैज्ञानिक अध्ययन हो । जणित सङ्ख्या संस्...,चञ्थ्थयनलाई अभिव्यक्त चटा स्याङ अध्ययन जण्नित...,0.406736,0.319689,0.621762,0.404145,0.520635,0.400000,0.749206,0.549206,nepali
25,Devanagari_Noto_Sans_6,अखामनी परम्पराद्वारा पाकिस्तानसँग भारोपेली विस...,अखामनी परम्पराद्वारा पाकिस्तानसँग भारोपेली विस...,अखामनी परम्पराद्वारा पाकिस्तानसँग भारोपेली विस...,अखामनी परम्पराद्वारा पाकिस्तानसँग भारोपेली विस...,अखामनी परम्पराद्वारा पाकिस्तानसँग भारोपेली विस...,0.154506,0.157845,0.259895,0.267048,0.229773,0.229773,0.330097,0.407767,nepali
26,Devanagari_Poppins_11,र has सामान्यतया मानिसले १९४८ Rtyuuuifमानव अधि...,र॥०5 सामान्यतया मानिसले 1948 छ सा न सबै मानुज...,न 0०5 सामान्यतया मानिसले 1948 र न मानव न सबै ...,र॥०5 सामान्यतया मानिसले 1948 बु ले पु पृ भन्न...,"अल ना का अपाङ्मता दश्निट अवधारणाहरु, मानव अधि...",0.723587,0.713307,0.741291,0.854940,0.910543,0.897764,0.936102,0.990415,nepali
27,Devanagari_Noto_Sans_20,"सकिन्छ। राष्ट्रभाषा. बाहेक डोगरी, भाषा राष्ट्र...","सकिन्छ। राष्ट्रभाषा. बाहेक डोगरी, भाषा राष्ट्...","सकिन्छ। राष्ट्रभाषा, बाहेक डोगरी, भाषा गा । व...","सकिन्छ। राष्ट्रभाषा, बाहेक डोगरी, भाषा हा गा ...","सकिन्छ। राष्ट्रभाषा, बाहेक डोगरी, भाषा वास्तव...",0.072545,0.084821,0.069196,0.323661,0.122222,0.137037,0.092593,0.429630,nepali